##
## Pipeline to run inside kubernetes runners
##
kind: pipeline
type: kubernetes
name: principal

steps:
  - name: construir imagenes
    image: plugins/docker
    #privileged: true
    settings:
      repo: albiworks/helidon-se-test
      username: ti3r.bubblenet@gmail.com
      password: a76d4c1d-8454-4c40-a1e8-6615991e4f8f
      tags:
        - latest
        - main
