##
## Pipeline to run inside kubernetes runners
##
kind: pipeline
type: kubernetes
name: principal

clone:
  disable: true


steps:
  - name: alt_clone
    image: drone/git
    user: 1000420000
    group: 1000420000
  - name: build_mvn
    image: maven:3-jdk-10
    commands:
      - mvn clean install
#  - name: construir imagenes
#    image: plugins/docker
#    user: 1000420000
#    group: 1000420000
#    settings:
#      repo: albiworks/helidon-se-test
#      username: ti3r.bubblenet@gmail.com
#      password: a76d4c1d-8454-4c40-a1e8-6615991e4f8f
#      tags:
#        - latest
#        - main
