format_version: 3
pipelines:
  helidon-se-test-pipeline:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      helidon-se-test:
        git: https://github.com/ti3r/helidon-se-test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - stage-1:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            job1:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - Starting pipeline
                    command: echo
                    run_if: passed
            job2:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - Hola Mundo!!!!
